import dataclasses


@dataclasses.dataclass(init=True)
class Match:
    id: int
    league: int
    custom: str
    season: int
    home: int
    time: str
    date: str
    away: int
    status: int
    scoreHome: int
    scoreAway: int
    homeName: str
    awayName: str


@dataclasses.dataclass(init=True)
class TeamPerformance:
    accurateCrosses: float
    accurateFinalThirdPassesAgainst: float
    accurateLongBalls: float
    accurateOppositionHalfPasses: float
    accurateOppositionHalfPassesAgainst: float
    accurateOwnHalfPasses: float
    accurateOwnHalfPassesAgainst: float
    accuratePasses: float
    accuratePassesAgainst: float
    aerialDuelsWon: float
    assists: float
    averageBallPossession: float
    avgRating: float
    awardedMatches: float
    bigChances: float
    bigChancesAgainst: float
    bigChancesCreated: float
    bigChancesCreatedAgainst: float
    bigChancesMissed: float
    bigChancesMissedAgainst: float
    cleanSheets: float
    clearances: float
    clearancesAgainst: float
    clearancesOffLine: float
    corners: float
    cornersAgainst: float
    crossesSuccessfulAgainst: float
    crossesTotalAgainst: float
    dribbleAttempts: float
    dribbleAttemptsTotalAgainst: float
    dribbleAttemptsWonAgainst: float
    duelsWon: float
    errorsLeadingToGoal: float
    errorsLeadingToGoalAgainst: float
    errorsLeadingToShot: float
    errorsLeadingToShotAgainst: float
    fastBreakGoals: float
    fastBreakShots: float
    fastBreaks: float
    fouls: float
    freeKickGoals: float
    freeKickShots: float
    goalsConceded: float
    goalsFromInsideTheBox: float
    goalsFromOutsideTheBox: float
    goalsScored: float
    groundDuelsWon: float
    headedGoals: float
    hitWoodwork: float
    hitWoodworkAgainst: float
    interceptions: float
    interceptionsAgainst: float
    keyPassesAgainst: float
    lastManTackles: float
    leftFootGoals: float
    longBallsSuccessfulAgainst: float
    longBallsTotalAgainst: float
    matches: float
    offsides: float
    offsidesAgainst: float
    oppositionHalfPassesTotalAgainst: float
    ownGoals: float
    ownHalfPassesTotalAgainst: float
    penaltiesCommited: float
    penaltiesTaken: float
    penaltyGoals: float
    penaltyGoalsConceded: float
    possessionLost: float
    redCards: float
    redCardsAgainst: float
    rightFootGoals: float
    saves: float
    shots: float
    shotsAgainst: float
    shotsBlockedAgainst: float
    shotsFromInsideTheBox: float
    shotsFromInsideTheBoxAgainst: float
    shotsFromOutsideTheBox: float
    shotsFromOutsideTheBoxAgainst: float
    shotsOffTarget: float
    shotsOffTargetAgainst: float
    shotsOnTarget: float
    shotsOnTargetAgainst: float
    successfulDribbles: float
    tackles: float
    tacklesAgainst: float
    totalAerialDuels: float
    totalCrosses: float
    totalDuels: float
    totalFinalThirdPassesAgainst: float
    totalGroundDuels: float
    totalLongBalls: float
    totalOppositionHalfPasses: float
    totalOwnHalfPasses: float
    totalPasses: float
    totalPassesAgainst: float
    yellowCards: float
    yellowCardsAgainst: float
    yellowRedCards: float
