import dataclasses

from model.football import Match, TeamPerformance


@dataclasses.dataclass()
class AwaitingResultsModel:
    accurateCrosses: float = 0.0
    accurateFinalThirdPassesAgainst: float = 0.0
    accurateLongBalls: float = 0.0
    accurateOppositionHalfPasses: float = 0.0
    accurateOppositionHalfPassesAgainst: float = 0.0
    accurateOwnHalfPasses: float = 0.0
    accurateOwnHalfPassesAgainst: float = 0.0
    accuratePasses: float = 0.0
    accuratePassesAgainst: float = 0.0
    aerialDuelsWon: float = 0.0
    assists: float = 0.0
    averageBallPossession: float = 0.0
    avgRating: float = 0.0
    awardedMatches: float = 0.0
    bigChances: float = 0.0
    bigChancesAgainst: float = 0.0
    bigChancesCreated: float = 0.0
    bigChancesCreatedAgainst: float = 0.0
    bigChancesMissed: float = 0.0
    bigChancesMissedAgainst: float = 0.0
    cleanSheets: float = 0.0
    clearances: float = 0.0
    clearancesAgainst: float = 0.0
    clearancesOffLine: float = 0.0
    corners: float = 0.0
    cornersAgainst: float = 0.0
    crossesSuccessfulAgainst: float = 0.0
    crossesTotalAgainst: float = 0.0
    dribbleAttempts: float = 0.0
    dribbleAttemptsTotalAgainst: float = 0.0
    dribbleAttemptsWonAgainst: float = 0.0
    duelsWon: float = 0.0
    errorsLeadingToGoal: float = 0.0
    errorsLeadingToGoalAgainst: float = 0.0
    errorsLeadingToShot: float = 0.0
    errorsLeadingToShotAgainst: float = 0.0
    fastBreakGoals: float = 0.0
    fastBreakShots: float = 0.0
    fastBreaks: float = 0.0
    fouls: float = 0.0
    freeKickGoals: float = 0.0
    freeKickShots: float = 0.0
    goalsConceded: float = 0.0
    goalsFromInsideTheBox: float = 0.0
    goalsFromOutsideTheBox: float = 0.0
    goalsScored: float = 0.0
    groundDuelsWon: float = 0.0
    headedGoals: float = 0.0
    hitWoodwork: float = 0.0
    hitWoodworkAgainst: float = 0.0
    interceptions: float = 0.0
    interceptionsAgainst: float = 0.0
    keyPassesAgainst: float = 0.0
    lastManTackles: float = 0.0
    leftFootGoals: float = 0.0
    longBallsSuccessfulAgainst: float = 0.0
    longBallsTotalAgainst: float = 0.0
    matches: float = 0.0
    offsides: float = 0.0
    offsidesAgainst: float = 0.0
    oppositionHalfPassesTotalAgainst: float = 0.0
    ownGoals: float = 0.0
    ownHalfPassesTotalAgainst: float = 0.0
    penaltiesCommited: float = 0.0
    penaltiesTaken: float = 0.0
    penaltyGoals: float = 0.0
    penaltyGoalsConceded: float = 0.0
    possessionLost: float = 0.0
    redCards: float = 0.0
    redCardsAgainst: float = 0.0
    rightFootGoals: float = 0.0
    saves: float = 0.0
    shots: float = 0.0
    shotsAgainst: float = 0.0
    shotsBlockedAgainst: float = 0.0
    shotsFromInsideTheBox: float = 0.0
    shotsFromInsideTheBoxAgainst: float = 0.0
    shotsFromOutsideTheBox: float = 0.0
    shotsFromOutsideTheBoxAgainst: float = 0.0
    shotsOffTarget: float = 0.0
    shotsOffTargetAgainst: float = 0.0
    shotsOnTarget: float = 0.0
    shotsOnTargetAgainst: float = 0.0
    successfulDribbles: float = 0.0
    tackles: float = 0.0
    tacklesAgainst: float = 0.0
    totalAerialDuels: float = 0.0
    totalCrosses: float = 0.0
    totalDuels: float = 0.0
    totalFinalThirdPassesAgainst: float = 0.0
    totalGroundDuels: float = 0.0
    totalLongBalls: float = 0.0
    totalOppositionHalfPasses: float = 0.0
    totalOwnHalfPasses: float = 0.0
    totalPasses: float = 0.0
    totalPassesAgainst: float = 0.0
    yellowCards: float = 0.0
    yellowCardsAgainst: float = 0.0
    yellowRedCards: float = 0.0
    id: int = 0

    def build_from_data(self, match: Match, home: TeamPerformance, away: TeamPerformance):
        self.id = match.id
        self.accurateCrosses = home.accurateCrosses - away.accurateCrosses
        self.accurateFinalThirdPassesAgainst = home.accurateFinalThirdPassesAgainst - away.accurateFinalThirdPassesAgainst
        self.accurateLongBalls = home.accurateLongBalls - away.accurateLongBalls
        self.accurateOppositionHalfPasses = home.accurateOppositionHalfPasses - away.accurateOppositionHalfPasses
        self.accurateOppositionHalfPassesAgainst = home.accurateOppositionHalfPassesAgainst - away.accurateOppositionHalfPassesAgainst
        self.accurateOwnHalfPasses = home.accurateOwnHalfPasses - away.accurateOwnHalfPasses
        self.accurateOwnHalfPassesAgainst = home.accurateOwnHalfPassesAgainst - away.accurateOwnHalfPassesAgainst
        self.accuratePasses = home.accuratePasses - away.accuratePasses
        self.accuratePassesAgainst = home.accuratePassesAgainst - away.accuratePassesAgainst
        self.aerialDuelsWon = home.aerialDuelsWon - away.aerialDuelsWon
        self.assists = home.assists - away.assists
        self.averageBallPossession = home.averageBallPossession - away.averageBallPossession
        self.avgRating = home.avgRating - away.avgRating
        self.awardedMatches = home.awardedMatches - away.awardedMatches
        self.bigChances = home.bigChances - away.bigChances
        self.bigChancesAgainst = home.bigChancesAgainst - away.bigChancesAgainst
        self.bigChancesCreated = home.bigChancesCreated - away.bigChancesCreated
        self.bigChancesCreatedAgainst = home.bigChancesCreatedAgainst - away.bigChancesCreatedAgainst
        self.bigChancesMissed = home.bigChancesMissed - away.bigChancesMissed
        self.bigChancesMissedAgainst = home.bigChancesMissedAgainst - away.bigChancesMissedAgainst
        self.cleanSheets = home.cleanSheets - away.cleanSheets
        self.clearances = home.clearances - away.clearances
        self.clearancesAgainst = home.clearancesAgainst - away.clearancesAgainst
        self.clearancesOffLine = home.clearancesOffLine - away.clearancesOffLine
        self.corners = home.corners - away.corners
        self.cornersAgainst = home.cornersAgainst - away.cornersAgainst
        self.crossesSuccessfulAgainst = home.crossesSuccessfulAgainst - away.crossesSuccessfulAgainst
        self.crossesTotalAgainst = home.crossesTotalAgainst - away.crossesTotalAgainst
        self.dribbleAttempts = home.dribbleAttempts - away.dribbleAttempts
        self.dribbleAttemptsTotalAgainst = home.dribbleAttemptsTotalAgainst - away.dribbleAttemptsTotalAgainst
        self.dribbleAttemptsWonAgainst = home.dribbleAttemptsWonAgainst - away.dribbleAttemptsWonAgainst
        self.duelsWon = home.duelsWon - away.duelsWon
        self.errorsLeadingToGoal = home.errorsLeadingToGoal - away.errorsLeadingToGoal
        self.errorsLeadingToGoalAgainst = home.errorsLeadingToGoalAgainst - away.errorsLeadingToGoalAgainst
        self.errorsLeadingToShot = home.errorsLeadingToShot - away.errorsLeadingToShot
        self.errorsLeadingToShotAgainst = home.errorsLeadingToShotAgainst - away.errorsLeadingToShotAgainst
        self.fastBreakGoals = home.fastBreakGoals - away.fastBreakGoals
        self.fastBreakShots = home.fastBreakShots - away.fastBreakShots
        self.fastBreaks = home.fastBreaks - away.fastBreaks
        self.fouls = home.fouls - away.fouls
        self.freeKickGoals = home.freeKickGoals - away.freeKickGoals
        self.freeKickShots = home.freeKickShots - away.freeKickShots
        self.goalsConceded = home.goalsConceded - away.goalsConceded
        self.goalsFromInsideTheBox = home.goalsFromInsideTheBox - away.goalsFromInsideTheBox
        self.goalsFromOutsideTheBox = home.goalsFromOutsideTheBox - away.goalsFromOutsideTheBox
        self.goalsScored = home.goalsScored - away.goalsScored
        self.groundDuelsWon = home.groundDuelsWon - away.groundDuelsWon
        self.headedGoals = home.headedGoals - away.headedGoals
        self.hitWoodwork = home.hitWoodwork - away.hitWoodwork
        self.hitWoodworkAgainst = home.hitWoodworkAgainst - away.hitWoodworkAgainst
        self.interceptions = home.interceptions - away.interceptions
        self.interceptionsAgainst = home.interceptionsAgainst - away.interceptionsAgainst
        self.keyPassesAgainst = home.keyPassesAgainst - away.keyPassesAgainst
        self.lastManTackles = home.lastManTackles - away.lastManTackles
        self.leftFootGoals = home.leftFootGoals - away.leftFootGoals
        self.longBallsSuccessfulAgainst = home.longBallsSuccessfulAgainst - away.longBallsSuccessfulAgainst
        self.longBallsTotalAgainst = home.longBallsTotalAgainst - away.longBallsTotalAgainst
        self.matches = home.matches - away.matches
        self.offsides = home.offsides - away.offsides
        self.offsidesAgainst = home.offsidesAgainst - away.offsidesAgainst
        self.oppositionHalfPassesTotalAgainst = home.oppositionHalfPassesTotalAgainst - away.oppositionHalfPassesTotalAgainst
        self.ownGoals = home.ownGoals - away.ownGoals
        self.ownHalfPassesTotalAgainst = home.ownHalfPassesTotalAgainst - away.ownHalfPassesTotalAgainst
        self.penaltiesCommited = home.penaltiesCommited - away.penaltiesCommited
        self.penaltiesTaken = home.penaltiesTaken - away.penaltiesTaken
        self.penaltyGoals = home.penaltyGoals - away.penaltyGoals
        self.penaltyGoalsConceded = home.penaltyGoalsConceded - away.penaltyGoalsConceded
        self.possessionLost = home.possessionLost - away.possessionLost
        self.redCards = home.redCards - away.redCards
        self.redCardsAgainst = home.redCardsAgainst - away.redCardsAgainst
        self.rightFootGoals = home.rightFootGoals - away.rightFootGoals
        self.saves = home.saves - away.saves
        self.shots = home.shots - away.shots
        self.shotsAgainst = home.shotsAgainst - away.shotsAgainst
        self.shotsBlockedAgainst = home.shotsBlockedAgainst - away.shotsBlockedAgainst
        self.shotsFromInsideTheBox = home.shotsFromInsideTheBox - away.shotsFromInsideTheBox
        self.shotsFromInsideTheBoxAgainst = home.shotsFromInsideTheBoxAgainst - away.shotsFromInsideTheBoxAgainst
        self.shotsFromOutsideTheBox = home.shotsFromOutsideTheBox - away.shotsFromOutsideTheBox
        self.shotsFromOutsideTheBoxAgainst = home.shotsFromOutsideTheBoxAgainst - away.shotsFromOutsideTheBoxAgainst
        self.shotsOffTarget = home.shotsOffTarget - away.shotsOffTarget
        self.shotsOffTargetAgainst = home.shotsOffTargetAgainst - away.shotsOffTargetAgainst
        self.shotsOnTarget = home.shotsOnTarget - away.shotsOnTarget
        self.shotsOnTargetAgainst = home.shotsOnTargetAgainst - away.shotsOnTargetAgainst
        self.successfulDribbles = home.successfulDribbles - away.successfulDribbles
        self.tackles = home.tackles - away.tackles
        self.tacklesAgainst = home.tacklesAgainst - away.tacklesAgainst
        self.totalAerialDuels = home.totalAerialDuels - away.totalAerialDuels
        self.totalCrosses = home.totalCrosses - away.totalCrosses
        self.totalDuels = home.totalDuels - away.totalDuels
        self.totalFinalThirdPassesAgainst = home.totalFinalThirdPassesAgainst - away.totalFinalThirdPassesAgainst
        self.totalGroundDuels = home.totalGroundDuels - away.totalGroundDuels
        self.totalLongBalls = home.totalLongBalls - away.totalLongBalls
        self.totalOppositionHalfPasses = home.totalOppositionHalfPasses - away.totalOppositionHalfPasses
        self.totalOwnHalfPasses = home.totalOwnHalfPasses - away.totalOwnHalfPasses
        self.totalPasses = home.totalPasses - away.totalPasses
        self.totalPassesAgainst = home.totalPassesAgainst - away.totalPassesAgainst
        self.yellowCards = home.yellowCards - away.yellowCards
        self.yellowCardsAgainst = home.yellowCardsAgainst - away.yellowCardsAgainst
        self.yellowRedCards = home.yellowRedCards - away.yellowRedCards

    def from_dict(self, performance: dict):
        self.id = performance['id']
        self.accurateCrosses = performance['accurateCrosses']
        self.accurateFinalThirdPassesAgainst = performance['accurateFinalThirdPassesAgainst']
        self.accurateLongBalls = performance['accurateLongBalls']
        self.accurateOppositionHalfPasses = performance['accurateOppositionHalfPasses']
        self.accurateOppositionHalfPassesAgainst = performance['accurateOppositionHalfPassesAgainst']
        self.accurateOwnHalfPasses = performance['accurateOwnHalfPasses']
        self.accurateOwnHalfPassesAgainst = performance['accurateOwnHalfPassesAgainst']
        self.accuratePasses = performance['accuratePasses']
        self.accuratePassesAgainst = performance['accuratePassesAgainst']
        self.aerialDuelsWon = performance['aerialDuelsWon']
        self.assists = performance['assists']
        self.averageBallPossession = performance['averageBallPossession']
        self.avgRating = performance['avgRating']
        self.awardedMatches = performance['awardedMatches']
        self.bigChances = performance['bigChances']
        self.bigChancesAgainst = performance['bigChancesAgainst']
        self.bigChancesCreated = performance['bigChancesCreated']
        self.bigChancesCreatedAgainst = performance['bigChancesCreatedAgainst']
        self.bigChancesMissed = performance['bigChancesMissed']
        self.bigChancesMissedAgainst = performance['bigChancesMissedAgainst']
        self.cleanSheets = performance['cleanSheets']
        self.clearances = performance['clearances']
        self.clearancesAgainst = performance['clearancesAgainst']
        self.clearancesOffLine = performance['clearancesOffLine']
        self.corners = performance['corners']
        self.cornersAgainst = performance['cornersAgainst']
        self.crossesSuccessfulAgainst = performance['crossesSuccessfulAgainst']
        self.crossesTotalAgainst = performance['crossesTotalAgainst']
        self.dribbleAttempts = performance['dribbleAttempts']
        self.dribbleAttemptsTotalAgainst = performance['dribbleAttemptsTotalAgainst']
        self.dribbleAttemptsWonAgainst = performance['dribbleAttemptsWonAgainst']
        self.duelsWon = performance['duelsWon']
        self.errorsLeadingToGoal = performance['errorsLeadingToGoal']
        self.errorsLeadingToGoalAgainst = performance['errorsLeadingToGoalAgainst']
        self.errorsLeadingToShot = performance['errorsLeadingToShot']
        self.errorsLeadingToShotAgainst = performance['errorsLeadingToShotAgainst']
        self.fastBreakGoals = performance['fastBreakGoals']
        self.fastBreakShots = performance['fastBreakShots']
        self.fastBreaks = performance['fastBreaks']
        self.fouls = performance['fouls']
        self.freeKickGoals = performance['freeKickGoals']
        self.freeKickShots = performance['freeKickShots']
        self.goalsConceded = performance['goalsConceded']
        self.goalsFromInsideTheBox = performance['goalsFromInsideTheBox']
        self.goalsFromOutsideTheBox = performance['goalsFromOutsideTheBox']
        self.goalsScored = performance['goalsScored']
        self.groundDuelsWon = performance['groundDuelsWon']
        self.headedGoals = performance['headedGoals']
        self.hitWoodwork = performance['hitWoodwork']
        self.hitWoodworkAgainst = performance['hitWoodworkAgainst']
        self.interceptions = performance['interceptions']
        self.interceptionsAgainst = performance['interceptionsAgainst']
        self.keyPassesAgainst = performance['keyPassesAgainst']
        self.lastManTackles = performance['lastManTackles']
        self.leftFootGoals = performance['leftFootGoals']
        self.longBallsSuccessfulAgainst = performance['longBallsSuccessfulAgainst']
        self.longBallsTotalAgainst = performance['longBallsTotalAgainst']
        self.matches = performance['matches']
        self.offsides = performance['offsides']
        self.offsidesAgainst = performance['offsidesAgainst']
        self.oppositionHalfPassesTotalAgainst = performance['oppositionHalfPassesTotalAgainst']
        self.ownGoals = performance['ownGoals']
        self.ownHalfPassesTotalAgainst = performance['ownHalfPassesTotalAgainst']
        self.penaltiesCommited = performance['penaltiesCommited']
        self.penaltiesTaken = performance['penaltiesTaken']
        self.penaltyGoals = performance['penaltyGoals']
        self.penaltyGoalsConceded = performance['penaltyGoalsConceded']
        self.possessionLost = performance['possessionLost']
        self.redCards = performance['redCards']
        self.redCardsAgainst = performance['redCardsAgainst']
        self.rightFootGoals = performance['rightFootGoals']
        self.saves = performance['saves']
        self.shots = performance['shots']
        self.shotsAgainst = performance['shotsAgainst']
        self.shotsBlockedAgainst = performance['shotsBlockedAgainst']
        self.shotsFromInsideTheBox = performance['shotsFromInsideTheBox']
        self.shotsFromInsideTheBoxAgainst = performance['shotsFromInsideTheBoxAgainst']
        self.shotsFromOutsideTheBox = performance['shotsFromOutsideTheBox']
        self.shotsFromOutsideTheBoxAgainst = performance['shotsFromOutsideTheBoxAgainst']
        self.shotsOffTarget = performance['shotsOffTarget']
        self.shotsOffTargetAgainst = performance['shotsOffTargetAgainst']
        self.shotsOnTarget = performance['shotsOnTarget']
        self.shotsOnTargetAgainst = performance['shotsOnTargetAgainst']
        self.successfulDribbles = performance['successfulDribbles']
        self.tackles = performance['tackles']
        self.tacklesAgainst = performance['tacklesAgainst']
        self.totalAerialDuels = performance['totalAerialDuels']
        self.totalCrosses = performance['totalCrosses']
        self.totalDuels = performance['totalDuels']
        self.totalFinalThirdPassesAgainst = performance['totalFinalThirdPassesAgainst']
        self.totalGroundDuels = performance['totalGroundDuels']
        self.totalLongBalls = performance['totalLongBalls']
        self.totalOppositionHalfPasses = performance['totalOppositionHalfPasses']
        self.totalOwnHalfPasses = performance['totalOwnHalfPasses']
        self.totalPasses = performance['totalPasses']
        self.totalPassesAgainst = performance['totalPassesAgainst']
        self.yellowCards = performance['yellowCards']
        self.yellowCardsAgainst = performance['yellowCardsAgainst']
        self.yellowRedCards = performance['yellowRedCards']


@dataclasses.dataclass()
class AiTrainingModel:
    accurateCrosses: float = 0.0
    accurateFinalThirdPassesAgainst: float = 0.0
    accurateLongBalls: float = 0.0
    accurateOppositionHalfPasses: float = 0.0
    accurateOppositionHalfPassesAgainst: float = 0.0
    accurateOwnHalfPasses: float = 0.0
    accurateOwnHalfPassesAgainst: float = 0.0
    accuratePasses: float = 0.0
    accuratePassesAgainst: float = 0.0
    aerialDuelsWon: float = 0.0
    assists: float = 0.0
    averageBallPossession: float = 0.0
    avgRating: float = 0.0
    awardedMatches: float = 0.0
    bigChances: float = 0.0
    bigChancesAgainst: float = 0.0
    bigChancesCreated: float = 0.0
    bigChancesCreatedAgainst: float = 0.0
    bigChancesMissed: float = 0.0
    bigChancesMissedAgainst: float = 0.0
    cleanSheets: float = 0.0
    clearances: float = 0.0
    clearancesAgainst: float = 0.0
    clearancesOffLine: float = 0.0
    corners: float = 0.0
    cornersAgainst: float = 0.0
    crossesSuccessfulAgainst: float = 0.0
    crossesTotalAgainst: float = 0.0
    dribbleAttempts: float = 0.0
    dribbleAttemptsTotalAgainst: float = 0.0
    dribbleAttemptsWonAgainst: float = 0.0
    duelsWon: float = 0.0
    errorsLeadingToGoal: float = 0.0
    errorsLeadingToGoalAgainst: float = 0.0
    errorsLeadingToShot: float = 0.0
    errorsLeadingToShotAgainst: float = 0.0
    fastBreakGoals: float = 0.0
    fastBreakShots: float = 0.0
    fastBreaks: float = 0.0
    fouls: float = 0.0
    freeKickGoals: float = 0.0
    freeKickShots: float = 0.0
    goalsConceded: float = 0.0
    goalsFromInsideTheBox: float = 0.0
    goalsFromOutsideTheBox: float = 0.0
    goalsScored: float = 0.0
    groundDuelsWon: float = 0.0
    headedGoals: float = 0.0
    hitWoodwork: float = 0.0
    hitWoodworkAgainst: float = 0.0
    interceptions: float = 0.0
    interceptionsAgainst: float = 0.0
    keyPassesAgainst: float = 0.0
    lastManTackles: float = 0.0
    leftFootGoals: float = 0.0
    longBallsSuccessfulAgainst: float = 0.0
    longBallsTotalAgainst: float = 0.0
    matches: float = 0.0
    offsides: float = 0.0
    offsidesAgainst: float = 0.0
    oppositionHalfPassesTotalAgainst: float = 0.0
    ownGoals: float = 0.0
    ownHalfPassesTotalAgainst: float = 0.0
    penaltiesCommited: float = 0.0
    penaltiesTaken: float = 0.0
    penaltyGoals: float = 0.0
    penaltyGoalsConceded: float = 0.0
    possessionLost: float = 0.0
    redCards: float = 0.0
    redCardsAgainst: float = 0.0
    rightFootGoals: float = 0.0
    saves: float = 0.0
    shots: float = 0.0
    shotsAgainst: float = 0.0
    shotsBlockedAgainst: float = 0.0
    shotsFromInsideTheBox: float = 0.0
    shotsFromInsideTheBoxAgainst: float = 0.0
    shotsFromOutsideTheBox: float = 0.0
    shotsFromOutsideTheBoxAgainst: float = 0.0
    shotsOffTarget: float = 0.0
    shotsOffTargetAgainst: float = 0.0
    shotsOnTarget: float = 0.0
    shotsOnTargetAgainst: float = 0.0
    successfulDribbles: float = 0.0
    tackles: float = 0.0
    tacklesAgainst: float = 0.0
    totalAerialDuels: float = 0.0
    totalCrosses: float = 0.0
    totalDuels: float = 0.0
    totalFinalThirdPassesAgainst: float = 0.0
    totalGroundDuels: float = 0.0
    totalLongBalls: float = 0.0
    totalOppositionHalfPasses: float = 0.0
    totalOwnHalfPasses: float = 0.0
    totalPasses: float = 0.0
    totalPassesAgainst: float = 0.0
    yellowCards: float = 0.0
    yellowCardsAgainst: float = 0.0
    yellowRedCards: float = 0.0
    home: int = 0
    draw: int = 0
    away: int = 0
    id: int = 0

    def build_model(self, match: Match, awaited: AwaitingResultsModel):
        if match.scoreHome > match.scoreAway:
            self.home = 1
        elif match.scoreHome < match.scoreAway:
            self.away = 1
        elif match.scoreHome == match.scoreAway:
            self.draw = 1
        self.id = awaited.id
        self.accurateCrosses = awaited.accurateCrosses
        self.accurateFinalThirdPassesAgainst = awaited.accurateFinalThirdPassesAgainst
        self.accurateLongBalls = awaited.accurateLongBalls
        self.accurateOppositionHalfPasses = awaited.accurateOppositionHalfPasses
        self.accurateOppositionHalfPassesAgainst = awaited.accurateOppositionHalfPassesAgainst
        self.accurateOwnHalfPasses = awaited.accurateOwnHalfPasses
        self.accurateOwnHalfPassesAgainst = awaited.accurateOwnHalfPassesAgainst
        self.accuratePasses = awaited.accuratePasses
        self.accuratePassesAgainst = awaited.accuratePassesAgainst
        self.aerialDuelsWon = awaited.aerialDuelsWon
        self.assists = awaited.assists
        self.averageBallPossession = awaited.averageBallPossession
        self.avgRating = awaited.avgRating
        self.awardedMatches = awaited.awardedMatches
        self.bigChances = awaited.bigChances
        self.bigChancesAgainst = awaited.bigChancesAgainst
        self.bigChancesCreated = awaited.bigChancesCreated
        self.bigChancesCreatedAgainst = awaited.bigChancesCreatedAgainst
        self.bigChancesMissed = awaited.bigChancesMissed
        self.bigChancesMissedAgainst = awaited.bigChancesMissedAgainst
        self.cleanSheets = awaited.cleanSheets
        self.clearances = awaited.clearances
        self.clearancesAgainst = awaited.clearancesAgainst
        self.clearancesOffLine = awaited.clearancesOffLine
        self.corners = awaited.corners
        self.cornersAgainst = awaited.cornersAgainst
        self.crossesSuccessfulAgainst = awaited.crossesSuccessfulAgainst
        self.crossesTotalAgainst = awaited.crossesTotalAgainst
        self.dribbleAttempts = awaited.dribbleAttempts
        self.dribbleAttemptsTotalAgainst = awaited.dribbleAttemptsTotalAgainst
        self.dribbleAttemptsWonAgainst = awaited.dribbleAttemptsWonAgainst
        self.duelsWon = awaited.duelsWon
        self.errorsLeadingToGoal = awaited.errorsLeadingToGoal
        self.errorsLeadingToGoalAgainst = awaited.errorsLeadingToGoalAgainst
        self.errorsLeadingToShot = awaited.errorsLeadingToShot
        self.errorsLeadingToShotAgainst = awaited.errorsLeadingToShotAgainst
        self.fastBreakGoals = awaited.fastBreakGoals
        self.fastBreakShots = awaited.fastBreakShots
        self.fastBreaks = awaited.fastBreaks
        self.fouls = awaited.fouls
        self.freeKickGoals = awaited.freeKickGoals
        self.freeKickShots = awaited.freeKickShots
        self.goalsConceded = awaited.goalsConceded
        self.goalsFromInsideTheBox = awaited.goalsFromInsideTheBox
        self.goalsFromOutsideTheBox = awaited.goalsFromOutsideTheBox
        self.goalsScored = awaited.goalsScored
        self.groundDuelsWon = awaited.groundDuelsWon
        self.headedGoals = awaited.headedGoals
        self.hitWoodwork = awaited.hitWoodwork
        self.hitWoodworkAgainst = awaited.hitWoodworkAgainst
        self.interceptions = awaited.interceptions
        self.interceptionsAgainst = awaited.interceptionsAgainst
        self.keyPassesAgainst = awaited.keyPassesAgainst
        self.lastManTackles = awaited.lastManTackles
        self.leftFootGoals = awaited.leftFootGoals
        self.longBallsSuccessfulAgainst = awaited.longBallsSuccessfulAgainst
        self.longBallsTotalAgainst = awaited.longBallsTotalAgainst
        self.matches = awaited.matches
        self.offsides = awaited.offsides
        self.offsidesAgainst = awaited.offsidesAgainst
        self.oppositionHalfPassesTotalAgainst = awaited.oppositionHalfPassesTotalAgainst
        self.ownGoals = awaited.ownGoals
        self.ownHalfPassesTotalAgainst = awaited.ownHalfPassesTotalAgainst
        self.penaltiesCommited = awaited.penaltiesCommited
        self.penaltiesTaken = awaited.penaltiesTaken
        self.penaltyGoals = awaited.penaltyGoals
        self.penaltyGoalsConceded = awaited.penaltyGoalsConceded
        self.possessionLost = awaited.possessionLost
        self.redCards = awaited.redCards
        self.redCardsAgainst = awaited.redCardsAgainst
        self.rightFootGoals = awaited.rightFootGoals
        self.saves = awaited.saves
        self.shots = awaited.shots
        self.shotsAgainst = awaited.shotsAgainst
        self.shotsBlockedAgainst = awaited.shotsBlockedAgainst
        self.shotsFromInsideTheBox = awaited.shotsFromInsideTheBox
        self.shotsFromInsideTheBoxAgainst = awaited.shotsFromInsideTheBoxAgainst
        self.shotsFromOutsideTheBox = awaited.shotsFromOutsideTheBox
        self.shotsFromOutsideTheBoxAgainst = awaited.shotsFromOutsideTheBoxAgainst
        self.shotsOffTarget = awaited.shotsOffTarget
        self.shotsOffTargetAgainst = awaited.shotsOffTargetAgainst
        self.shotsOnTarget = awaited.shotsOnTarget
        self.shotsOnTargetAgainst = awaited.shotsOnTargetAgainst
        self.successfulDribbles = awaited.successfulDribbles
        self.tackles = awaited.tackles
        self.tacklesAgainst = awaited.tacklesAgainst
        self.totalAerialDuels = awaited.totalAerialDuels
        self.totalCrosses = awaited.totalCrosses
        self.totalDuels = awaited.totalDuels
        self.totalFinalThirdPassesAgainst = awaited.totalFinalThirdPassesAgainst
        self.totalGroundDuels = awaited.totalGroundDuels
        self.totalLongBalls = awaited.totalLongBalls
        self.totalOppositionHalfPasses = awaited.totalOppositionHalfPasses
        self.totalOwnHalfPasses = awaited.totalOwnHalfPasses
        self.totalPasses = awaited.totalPasses
        self.totalPassesAgainst = awaited.totalPassesAgainst
        self.yellowCards = awaited.yellowCards
        self.yellowCardsAgainst = awaited.yellowCardsAgainst
        self.yellowRedCards = awaited.yellowRedCards


@dataclasses.dataclass()
class AiBothScoreModel:
    accurateCrosses: float = 0.0
    accurateFinalThirdPassesAgainst: float = 0.0
    accurateLongBalls: float = 0.0
    accurateOppositionHalfPasses: float = 0.0
    accurateOppositionHalfPassesAgainst: float = 0.0
    accurateOwnHalfPasses: float = 0.0
    accurateOwnHalfPassesAgainst: float = 0.0
    accuratePasses: float = 0.0
    accuratePassesAgainst: float = 0.0
    aerialDuelsWon: float = 0.0
    assists: float = 0.0
    averageBallPossession: float = 0.0
    avgRating: float = 0.0
    awardedMatches: float = 0.0
    bigChances: float = 0.0
    bigChancesAgainst: float = 0.0
    bigChancesCreated: float = 0.0
    bigChancesCreatedAgainst: float = 0.0
    bigChancesMissed: float = 0.0
    bigChancesMissedAgainst: float = 0.0
    cleanSheets: float = 0.0
    clearances: float = 0.0
    clearancesAgainst: float = 0.0
    clearancesOffLine: float = 0.0
    corners: float = 0.0
    cornersAgainst: float = 0.0
    crossesSuccessfulAgainst: float = 0.0
    crossesTotalAgainst: float = 0.0
    dribbleAttempts: float = 0.0
    dribbleAttemptsTotalAgainst: float = 0.0
    dribbleAttemptsWonAgainst: float = 0.0
    duelsWon: float = 0.0
    errorsLeadingToGoal: float = 0.0
    errorsLeadingToGoalAgainst: float = 0.0
    errorsLeadingToShot: float = 0.0
    errorsLeadingToShotAgainst: float = 0.0
    fastBreakGoals: float = 0.0
    fastBreakShots: float = 0.0
    fastBreaks: float = 0.0
    fouls: float = 0.0
    freeKickGoals: float = 0.0
    freeKickShots: float = 0.0
    goalsConceded: float = 0.0
    goalsFromInsideTheBox: float = 0.0
    goalsFromOutsideTheBox: float = 0.0
    goalsScored: float = 0.0
    groundDuelsWon: float = 0.0
    headedGoals: float = 0.0
    hitWoodwork: float = 0.0
    hitWoodworkAgainst: float = 0.0
    interceptions: float = 0.0
    interceptionsAgainst: float = 0.0
    keyPassesAgainst: float = 0.0
    lastManTackles: float = 0.0
    leftFootGoals: float = 0.0
    longBallsSuccessfulAgainst: float = 0.0
    longBallsTotalAgainst: float = 0.0
    matches: float = 0.0
    offsides: float = 0.0
    offsidesAgainst: float = 0.0
    oppositionHalfPassesTotalAgainst: float = 0.0
    ownGoals: float = 0.0
    ownHalfPassesTotalAgainst: float = 0.0
    penaltiesCommited: float = 0.0
    penaltiesTaken: float = 0.0
    penaltyGoals: float = 0.0
    penaltyGoalsConceded: float = 0.0
    possessionLost: float = 0.0
    redCards: float = 0.0
    redCardsAgainst: float = 0.0
    rightFootGoals: float = 0.0
    saves: float = 0.0
    shots: float = 0.0
    shotsAgainst: float = 0.0
    shotsBlockedAgainst: float = 0.0
    shotsFromInsideTheBox: float = 0.0
    shotsFromInsideTheBoxAgainst: float = 0.0
    shotsFromOutsideTheBox: float = 0.0
    shotsFromOutsideTheBoxAgainst: float = 0.0
    shotsOffTarget: float = 0.0
    shotsOffTargetAgainst: float = 0.0
    shotsOnTarget: float = 0.0
    shotsOnTargetAgainst: float = 0.0
    successfulDribbles: float = 0.0
    tackles: float = 0.0
    tacklesAgainst: float = 0.0
    totalAerialDuels: float = 0.0
    totalCrosses: float = 0.0
    totalDuels: float = 0.0
    totalFinalThirdPassesAgainst: float = 0.0
    totalGroundDuels: float = 0.0
    totalLongBalls: float = 0.0
    totalOppositionHalfPasses: float = 0.0
    totalOwnHalfPasses: float = 0.0
    totalPasses: float = 0.0
    totalPassesAgainst: float = 0.0
    yellowCards: float = 0.0
    yellowCardsAgainst: float = 0.0
    yellowRedCards: float = 0.0
    result: int = 0
    id: int = 0

    def build_model(self, match: Match, awaited: AwaitingResultsModel):
        if match.scoreHome > 0 and match.scoreAway > 0:
            self.result = 1
        self.id = awaited.id
        self.accurateCrosses = awaited.accurateCrosses
        self.accurateFinalThirdPassesAgainst = awaited.accurateFinalThirdPassesAgainst
        self.accurateLongBalls = awaited.accurateLongBalls
        self.accurateOppositionHalfPasses = awaited.accurateOppositionHalfPasses
        self.accurateOppositionHalfPassesAgainst = awaited.accurateOppositionHalfPassesAgainst
        self.accurateOwnHalfPasses = awaited.accurateOwnHalfPasses
        self.accurateOwnHalfPassesAgainst = awaited.accurateOwnHalfPassesAgainst
        self.accuratePasses = awaited.accuratePasses
        self.accuratePassesAgainst = awaited.accuratePassesAgainst
        self.aerialDuelsWon = awaited.aerialDuelsWon
        self.assists = awaited.assists
        self.averageBallPossession = awaited.averageBallPossession
        self.avgRating = awaited.avgRating
        self.awardedMatches = awaited.awardedMatches
        self.bigChances = awaited.bigChances
        self.bigChancesAgainst = awaited.bigChancesAgainst
        self.bigChancesCreated = awaited.bigChancesCreated
        self.bigChancesCreatedAgainst = awaited.bigChancesCreatedAgainst
        self.bigChancesMissed = awaited.bigChancesMissed
        self.bigChancesMissedAgainst = awaited.bigChancesMissedAgainst
        self.cleanSheets = awaited.cleanSheets
        self.clearances = awaited.clearances
        self.clearancesAgainst = awaited.clearancesAgainst
        self.clearancesOffLine = awaited.clearancesOffLine
        self.corners = awaited.corners
        self.cornersAgainst = awaited.cornersAgainst
        self.crossesSuccessfulAgainst = awaited.crossesSuccessfulAgainst
        self.crossesTotalAgainst = awaited.crossesTotalAgainst
        self.dribbleAttempts = awaited.dribbleAttempts
        self.dribbleAttemptsTotalAgainst = awaited.dribbleAttemptsTotalAgainst
        self.dribbleAttemptsWonAgainst = awaited.dribbleAttemptsWonAgainst
        self.duelsWon = awaited.duelsWon
        self.errorsLeadingToGoal = awaited.errorsLeadingToGoal
        self.errorsLeadingToGoalAgainst = awaited.errorsLeadingToGoalAgainst
        self.errorsLeadingToShot = awaited.errorsLeadingToShot
        self.errorsLeadingToShotAgainst = awaited.errorsLeadingToShotAgainst
        self.fastBreakGoals = awaited.fastBreakGoals
        self.fastBreakShots = awaited.fastBreakShots
        self.fastBreaks = awaited.fastBreaks
        self.fouls = awaited.fouls
        self.freeKickGoals = awaited.freeKickGoals
        self.freeKickShots = awaited.freeKickShots
        self.goalsConceded = awaited.goalsConceded
        self.goalsFromInsideTheBox = awaited.goalsFromInsideTheBox
        self.goalsFromOutsideTheBox = awaited.goalsFromOutsideTheBox
        self.goalsScored = awaited.goalsScored
        self.groundDuelsWon = awaited.groundDuelsWon
        self.headedGoals = awaited.headedGoals
        self.hitWoodwork = awaited.hitWoodwork
        self.hitWoodworkAgainst = awaited.hitWoodworkAgainst
        self.interceptions = awaited.interceptions
        self.interceptionsAgainst = awaited.interceptionsAgainst
        self.keyPassesAgainst = awaited.keyPassesAgainst
        self.lastManTackles = awaited.lastManTackles
        self.leftFootGoals = awaited.leftFootGoals
        self.longBallsSuccessfulAgainst = awaited.longBallsSuccessfulAgainst
        self.longBallsTotalAgainst = awaited.longBallsTotalAgainst
        self.matches = awaited.matches
        self.offsides = awaited.offsides
        self.offsidesAgainst = awaited.offsidesAgainst
        self.oppositionHalfPassesTotalAgainst = awaited.oppositionHalfPassesTotalAgainst
        self.ownGoals = awaited.ownGoals
        self.ownHalfPassesTotalAgainst = awaited.ownHalfPassesTotalAgainst
        self.penaltiesCommited = awaited.penaltiesCommited
        self.penaltiesTaken = awaited.penaltiesTaken
        self.penaltyGoals = awaited.penaltyGoals
        self.penaltyGoalsConceded = awaited.penaltyGoalsConceded
        self.possessionLost = awaited.possessionLost
        self.redCards = awaited.redCards
        self.redCardsAgainst = awaited.redCardsAgainst
        self.rightFootGoals = awaited.rightFootGoals
        self.saves = awaited.saves
        self.shots = awaited.shots
        self.shotsAgainst = awaited.shotsAgainst
        self.shotsBlockedAgainst = awaited.shotsBlockedAgainst
        self.shotsFromInsideTheBox = awaited.shotsFromInsideTheBox
        self.shotsFromInsideTheBoxAgainst = awaited.shotsFromInsideTheBoxAgainst
        self.shotsFromOutsideTheBox = awaited.shotsFromOutsideTheBox
        self.shotsFromOutsideTheBoxAgainst = awaited.shotsFromOutsideTheBoxAgainst
        self.shotsOffTarget = awaited.shotsOffTarget
        self.shotsOffTargetAgainst = awaited.shotsOffTargetAgainst
        self.shotsOnTarget = awaited.shotsOnTarget
        self.shotsOnTargetAgainst = awaited.shotsOnTargetAgainst
        self.successfulDribbles = awaited.successfulDribbles
        self.tackles = awaited.tackles
        self.tacklesAgainst = awaited.tacklesAgainst
        self.totalAerialDuels = awaited.totalAerialDuels
        self.totalCrosses = awaited.totalCrosses
        self.totalDuels = awaited.totalDuels
        self.totalFinalThirdPassesAgainst = awaited.totalFinalThirdPassesAgainst
        self.totalGroundDuels = awaited.totalGroundDuels
        self.totalLongBalls = awaited.totalLongBalls
        self.totalOppositionHalfPasses = awaited.totalOppositionHalfPasses
        self.totalOwnHalfPasses = awaited.totalOwnHalfPasses
        self.totalPasses = awaited.totalPasses
        self.totalPassesAgainst = awaited.totalPassesAgainst
        self.yellowCards = awaited.yellowCards
        self.yellowCardsAgainst = awaited.yellowCardsAgainst
        self.yellowRedCards = awaited.yellowRedCards


@dataclasses.dataclass()
class AiPredictionModel:
    accurateCrosses: float = 0.0
    accurateFinalThirdPassesAgainst: float = 0.0
    accurateLongBalls: float = 0.0
    accurateOppositionHalfPasses: float = 0.0
    accurateOppositionHalfPassesAgainst: float = 0.0
    accurateOwnHalfPasses: float = 0.0
    accurateOwnHalfPassesAgainst: float = 0.0
    accuratePasses: float = 0.0
    accuratePassesAgainst: float = 0.0
    aerialDuelsWon: float = 0.0
    assists: float = 0.0
    averageBallPossession: float = 0.0
    avgRating: float = 0.0
    awardedMatches: float = 0.0
    bigChances: float = 0.0
    bigChancesAgainst: float = 0.0
    bigChancesCreated: float = 0.0
    bigChancesCreatedAgainst: float = 0.0
    bigChancesMissed: float = 0.0
    bigChancesMissedAgainst: float = 0.0
    cleanSheets: float = 0.0
    clearances: float = 0.0
    clearancesAgainst: float = 0.0
    clearancesOffLine: float = 0.0
    corners: float = 0.0
    cornersAgainst: float = 0.0
    crossesSuccessfulAgainst: float = 0.0
    crossesTotalAgainst: float = 0.0
    dribbleAttempts: float = 0.0
    dribbleAttemptsTotalAgainst: float = 0.0
    dribbleAttemptsWonAgainst: float = 0.0
    duelsWon: float = 0.0
    errorsLeadingToGoal: float = 0.0
    errorsLeadingToGoalAgainst: float = 0.0
    errorsLeadingToShot: float = 0.0
    errorsLeadingToShotAgainst: float = 0.0
    fastBreakGoals: float = 0.0
    fastBreakShots: float = 0.0
    fastBreaks: float = 0.0
    fouls: float = 0.0
    freeKickGoals: float = 0.0
    freeKickShots: float = 0.0
    goalsConceded: float = 0.0
    goalsFromInsideTheBox: float = 0.0
    goalsFromOutsideTheBox: float = 0.0
    goalsScored: float = 0.0
    groundDuelsWon: float = 0.0
    headedGoals: float = 0.0
    hitWoodwork: float = 0.0
    hitWoodworkAgainst: float = 0.0
    interceptions: float = 0.0
    interceptionsAgainst: float = 0.0
    keyPassesAgainst: float = 0.0
    lastManTackles: float = 0.0
    leftFootGoals: float = 0.0
    longBallsSuccessfulAgainst: float = 0.0
    longBallsTotalAgainst: float = 0.0
    matches: float = 0.0
    offsides: float = 0.0
    offsidesAgainst: float = 0.0
    oppositionHalfPassesTotalAgainst: float = 0.0
    ownGoals: float = 0.0
    ownHalfPassesTotalAgainst: float = 0.0
    penaltiesCommited: float = 0.0
    penaltiesTaken: float = 0.0
    penaltyGoals: float = 0.0
    penaltyGoalsConceded: float = 0.0
    possessionLost: float = 0.0
    redCards: float = 0.0
    redCardsAgainst: float = 0.0
    rightFootGoals: float = 0.0
    saves: float = 0.0
    shots: float = 0.0
    shotsAgainst: float = 0.0
    shotsBlockedAgainst: float = 0.0
    shotsFromInsideTheBox: float = 0.0
    shotsFromInsideTheBoxAgainst: float = 0.0
    shotsFromOutsideTheBox: float = 0.0
    shotsFromOutsideTheBoxAgainst: float = 0.0
    shotsOffTarget: float = 0.0
    shotsOffTargetAgainst: float = 0.0
    shotsOnTarget: float = 0.0
    shotsOnTargetAgainst: float = 0.0
    successfulDribbles: float = 0.0
    tackles: float = 0.0
    tacklesAgainst: float = 0.0
    totalAerialDuels: float = 0.0
    totalCrosses: float = 0.0
    totalDuels: float = 0.0
    totalFinalThirdPassesAgainst: float = 0.0
    totalGroundDuels: float = 0.0
    totalLongBalls: float = 0.0
    totalOppositionHalfPasses: float = 0.0
    totalOwnHalfPasses: float = 0.0
    totalPasses: float = 0.0
    totalPassesAgainst: float = 0.0
    yellowCards: float = 0.0
    yellowCardsAgainst: float = 0.0
    yellowRedCards: float = 0.0
    id: int = 0

    def build_model(self, awaited: AwaitingResultsModel):
        self.id = awaited.id
        self.accurateCrosses = awaited.accurateCrosses
        self.accurateFinalThirdPassesAgainst = awaited.accurateFinalThirdPassesAgainst
        self.accurateLongBalls = awaited.accurateLongBalls
        self.accurateOppositionHalfPasses = awaited.accurateOppositionHalfPasses
        self.accurateOppositionHalfPassesAgainst = awaited.accurateOppositionHalfPassesAgainst
        self.accurateOwnHalfPasses = awaited.accurateOwnHalfPasses
        self.accurateOwnHalfPassesAgainst = awaited.accurateOwnHalfPassesAgainst
        self.accuratePasses = awaited.accuratePasses
        self.accuratePassesAgainst = awaited.accuratePassesAgainst
        self.aerialDuelsWon = awaited.aerialDuelsWon
        self.assists = awaited.assists
        self.averageBallPossession = awaited.averageBallPossession
        self.avgRating = awaited.avgRating
        self.awardedMatches = awaited.awardedMatches
        self.bigChances = awaited.bigChances
        self.bigChancesAgainst = awaited.bigChancesAgainst
        self.bigChancesCreated = awaited.bigChancesCreated
        self.bigChancesCreatedAgainst = awaited.bigChancesCreatedAgainst
        self.bigChancesMissed = awaited.bigChancesMissed
        self.bigChancesMissedAgainst = awaited.bigChancesMissedAgainst
        self.cleanSheets = awaited.cleanSheets
        self.clearances = awaited.clearances
        self.clearancesAgainst = awaited.clearancesAgainst
        self.clearancesOffLine = awaited.clearancesOffLine
        self.corners = awaited.corners
        self.cornersAgainst = awaited.cornersAgainst
        self.crossesSuccessfulAgainst = awaited.crossesSuccessfulAgainst
        self.crossesTotalAgainst = awaited.crossesTotalAgainst
        self.dribbleAttempts = awaited.dribbleAttempts
        self.dribbleAttemptsTotalAgainst = awaited.dribbleAttemptsTotalAgainst
        self.dribbleAttemptsWonAgainst = awaited.dribbleAttemptsWonAgainst
        self.duelsWon = awaited.duelsWon
        self.errorsLeadingToGoal = awaited.errorsLeadingToGoal
        self.errorsLeadingToGoalAgainst = awaited.errorsLeadingToGoalAgainst
        self.errorsLeadingToShot = awaited.errorsLeadingToShot
        self.errorsLeadingToShotAgainst = awaited.errorsLeadingToShotAgainst
        self.fastBreakGoals = awaited.fastBreakGoals
        self.fastBreakShots = awaited.fastBreakShots
        self.fastBreaks = awaited.fastBreaks
        self.fouls = awaited.fouls
        self.freeKickGoals = awaited.freeKickGoals
        self.freeKickShots = awaited.freeKickShots
        self.goalsConceded = awaited.goalsConceded
        self.goalsFromInsideTheBox = awaited.goalsFromInsideTheBox
        self.goalsFromOutsideTheBox = awaited.goalsFromOutsideTheBox
        self.goalsScored = awaited.goalsScored
        self.groundDuelsWon = awaited.groundDuelsWon
        self.headedGoals = awaited.headedGoals
        self.hitWoodwork = awaited.hitWoodwork
        self.hitWoodworkAgainst = awaited.hitWoodworkAgainst
        self.interceptions = awaited.interceptions
        self.interceptionsAgainst = awaited.interceptionsAgainst
        self.keyPassesAgainst = awaited.keyPassesAgainst
        self.lastManTackles = awaited.lastManTackles
        self.leftFootGoals = awaited.leftFootGoals
        self.longBallsSuccessfulAgainst = awaited.longBallsSuccessfulAgainst
        self.longBallsTotalAgainst = awaited.longBallsTotalAgainst
        self.matches = awaited.matches
        self.offsides = awaited.offsides
        self.offsidesAgainst = awaited.offsidesAgainst
        self.oppositionHalfPassesTotalAgainst = awaited.oppositionHalfPassesTotalAgainst
        self.ownGoals = awaited.ownGoals
        self.ownHalfPassesTotalAgainst = awaited.ownHalfPassesTotalAgainst
        self.penaltiesCommited = awaited.penaltiesCommited
        self.penaltiesTaken = awaited.penaltiesTaken
        self.penaltyGoals = awaited.penaltyGoals
        self.penaltyGoalsConceded = awaited.penaltyGoalsConceded
        self.possessionLost = awaited.possessionLost
        self.redCards = awaited.redCards
        self.redCardsAgainst = awaited.redCardsAgainst
        self.rightFootGoals = awaited.rightFootGoals
        self.saves = awaited.saves
        self.shots = awaited.shots
        self.shotsAgainst = awaited.shotsAgainst
        self.shotsBlockedAgainst = awaited.shotsBlockedAgainst
        self.shotsFromInsideTheBox = awaited.shotsFromInsideTheBox
        self.shotsFromInsideTheBoxAgainst = awaited.shotsFromInsideTheBoxAgainst
        self.shotsFromOutsideTheBox = awaited.shotsFromOutsideTheBox
        self.shotsFromOutsideTheBoxAgainst = awaited.shotsFromOutsideTheBoxAgainst
        self.shotsOffTarget = awaited.shotsOffTarget
        self.shotsOffTargetAgainst = awaited.shotsOffTargetAgainst
        self.shotsOnTarget = awaited.shotsOnTarget
        self.shotsOnTargetAgainst = awaited.shotsOnTargetAgainst
        self.successfulDribbles = awaited.successfulDribbles
        self.tackles = awaited.tackles
        self.tacklesAgainst = awaited.tacklesAgainst
        self.totalAerialDuels = awaited.totalAerialDuels
        self.totalCrosses = awaited.totalCrosses
        self.totalDuels = awaited.totalDuels
        self.totalFinalThirdPassesAgainst = awaited.totalFinalThirdPassesAgainst
        self.totalGroundDuels = awaited.totalGroundDuels
        self.totalLongBalls = awaited.totalLongBalls
        self.totalOppositionHalfPasses = awaited.totalOppositionHalfPasses
        self.totalOwnHalfPasses = awaited.totalOwnHalfPasses
        self.totalPasses = awaited.totalPasses
        self.totalPassesAgainst = awaited.totalPassesAgainst
        self.yellowCards = awaited.yellowCards
        self.yellowCardsAgainst = awaited.yellowCardsAgainst
        self.yellowRedCards = awaited.yellowRedCards


@dataclasses.dataclass()
class AiPredictionResult:
    home: str
    away: str
    homeWin: str
    draw: str
    awayWin: str
    time: str
    bothToScore: str
    date: str
